name: codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: 3.7
    - name: Generate Report
      run: |
        pip install --user -r requirements.txt
        pip install --user -r requirements_dev.txt
        coverage run -m unittest

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    #- name: Upload Coverage to Codecov
    #  uses: codecov/codecov-action@v3.1.1